2021-10-22 16:21:48 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.TseApi.Supervisor'}
     Context:    start_error
     Reason:     {'EXIT',{undef,[{'Elixir.TSE.Consumer',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,379}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,349}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1157}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,315}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]}]}}
     Offender:   [{pid,undefined},{id,'Elixir.TSE.Consumer'},{mfargs,{'Elixir.TSE.Consumer',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2021-10-22 16:21:48 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.331.0>
    registered_name: []
    exception exit: {{{shutdown,{failed_to_start_child,'Elixir.TSE.Consumer',{'EXIT',{undef,[{'Elixir.TSE.Consumer',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,379}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,349}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1157}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,315}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]}]}}}},{'Elixir.TseApi.Application',start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [<0.330.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.332.0>,normal}]
    links: [<0.330.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 243
  neighbours:
2021-10-22 16:23:33 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.324.0>
    registered_name: []
    exception exit: {{bad_return,{{'Elixir.TseApi.Application',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<"supervisors expect each child to be one of the following:\n\n  * a module\n  * a {module, arg} tuple\n  * a child specification as a map with at least the :id and :start fields\n  * or a tuple with 6 elements generated by Supervisor.Spec (deprecated)\n\nGot: {TSE.Consumer}\n">>},[{'Elixir.Supervisor',init_child,1,[{file,"lib/supervisor.ex"},{line,648}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1553}]},{'Elixir.Enum','-map/2-lists^map/1-0-',2,[{file,"lib/enum.ex"},{line,1553}]},{'Elixir.Supervisor',init,2,[{file,"lib/supervisor.ex"},{line,617}]},{'Elixir.Supervisor',start_link,2,[{file,"lib/supervisor.ex"},{line,556}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,277}]}]}}}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [<0.323.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.325.0>,normal}]
    links: [<0.323.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 239
  neighbours:
2021-10-22 16:25:48 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.TseApi.Supervisor'}
     Context:    start_error
     Reason:     {{badmatch,{ok,#{consumer_count => 0,message_count => 0,queue => <<"chung_khoan_co_so_queue">>}}},[{'Elixir.TSE.Consumer',setup_exchange,1,[{file,"lib/tse_api/consumer.ex"},{line,41}]},{'Elixir.TSE.Consumer',init,1,[{file,"lib/tse_api/consumer.ex"},{line,16}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
     Offender:   [{pid,undefined},{id,'Elixir.TSE.Consumer'},{mfargs,{'Elixir.TSE.Consumer',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2021-10-22 16:25:48 =CRASH REPORT====
  crasher:
    initial call: Elixir.TSE.Consumer:init/1
    pid: <0.351.0>
    registered_name: []
    exception error: {{badmatch,{ok,#{consumer_count => 0,message_count => 0,queue => <<"chung_khoan_co_so_queue">>}}},[{'Elixir.TSE.Consumer',setup_exchange,1,[{file,"lib/tse_api/consumer.ex"},{line,41}]},{'Elixir.TSE.Consumer',init,1,[{file,"lib/tse_api/consumer.ex"},{line,16}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: ['Elixir.TseApi.Supervisor',<0.331.0>]
    message_queue_len: 0
    messages: []
    links: [<0.332.0>]
    dictionary: [{gen_server_call_timeout,70000}]
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 44180
  neighbours:
2021-10-22 16:25:48 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.330.0>
    registered_name: []
    exception exit: {{{shutdown,{failed_to_start_child,'Elixir.TSE.Consumer',{{badmatch,{ok,#{consumer_count => 0,message_count => 0,queue => <<"chung_khoan_co_so_queue">>}}},[{'Elixir.TSE.Consumer',setup_exchange,1,[{file,"lib/tse_api/consumer.ex"},{line,41}]},{'Elixir.TSE.Consumer',init,1,[{file,"lib/tse_api/consumer.ex"},{line,16}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}}},{'Elixir.TseApi.Application',start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [<0.329.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.331.0>,normal}]
    links: [<0.329.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 225
  neighbours:
2021-10-22 16:29:58 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.TseApi.Supervisor'}
     Context:    start_error
     Reason:     {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'tse_exchange' in vhost 'fffdmiik': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.365.0>,{call,{'exchange.declare',0,<<"tse_exchange">>,<<"fanout">>,false,true,false,false,false,[]},none,<0.346.0>},70000]}}
     Offender:   [{pid,undefined},{id,'Elixir.TSE.Consumer'},{mfargs,{'Elixir.TSE.Consumer',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2021-10-22 16:29:58 =CRASH REPORT====
  crasher:
    initial call: Elixir.TSE.Consumer:init/1
    pid: <0.346.0>
    registered_name: []
    exception exit: {{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'tse_exchange' in vhost 'fffdmiik': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.365.0>,{call,{'exchange.declare',0,<<"tse_exchange">>,<<"fanout">>,false,true,false,false,false,[]},none,<0.346.0>},70000]}},[{gen_server,call,3,[{file,"gen_server.erl"},{line,223}]},{'Elixir.AMQP.Exchange',declare,4,[{file,"lib/amqp/exchange.ex"},{line,48}]},{'Elixir.TSE.Consumer',setup_exchange,1,[{file,"lib/tse_api/consumer.ex"},{line,48}]},{'Elixir.TSE.Consumer',init,1,[{file,"lib/tse_api/consumer.ex"},{line,17}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: ['Elixir.TseApi.Supervisor',<0.326.0>]
    message_queue_len: 0
    messages: []
    links: [<0.327.0>]
    dictionary: [{gen_server_call_timeout,70000}]
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 45033
  neighbours:
2021-10-22 16:29:58 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.325.0>
    registered_name: []
    exception exit: {{{shutdown,{failed_to_start_child,'Elixir.TSE.Consumer',{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'tse_exchange' in vhost 'fffdmiik': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.365.0>,{call,{'exchange.declare',0,<<"tse_exchange">>,<<"fanout">>,false,true,false,false,false,[]},none,<0.346.0>},70000]}}}},{'Elixir.TseApi.Application',start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [<0.324.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.326.0>,normal}]
    links: [<0.324.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 219
  neighbours:
2021-10-22 16:41:10 =CRASH REPORT====
  crasher:
    initial call: Elixir.TSE.Consumer:init/1
    pid: <0.346.0>
    registered_name: []
    exception exit: {{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'tse_exchange' in vhost 'fffdmiik': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.365.0>,{call,{'exchange.declare',0,<<"tse_exchange">>,<<"fanout">>,false,true,false,false,false,[]},none,<0.346.0>},70000]}},[{gen_server,call,3,[{file,"gen_server.erl"},{line,223}]},{'Elixir.AMQP.Exchange',declare,4,[{file,"lib/amqp/exchange.ex"},{line,48}]},{'Elixir.TSE.Consumer',setup_exchange,1,[{file,"lib/tse_api/consumer.ex"},{line,48}]},{'Elixir.TSE.Consumer',init,1,[{file,"lib/tse_api/consumer.ex"},{line,17}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: ['Elixir.TseApi.Supervisor',<0.326.0>]
    message_queue_len: 0
    messages: []
    links: [<0.327.0>]
    dictionary: [{gen_server_call_timeout,70000}]
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 45034
  neighbours:
2021-10-22 16:41:10 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.TseApi.Supervisor'}
     Context:    start_error
     Reason:     {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'tse_exchange' in vhost 'fffdmiik': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.365.0>,{call,{'exchange.declare',0,<<"tse_exchange">>,<<"fanout">>,false,true,false,false,false,[]},none,<0.346.0>},70000]}}
     Offender:   [{pid,undefined},{id,'Elixir.TSE.Consumer'},{mfargs,{'Elixir.TSE.Consumer',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2021-10-22 16:41:10 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.325.0>
    registered_name: []
    exception exit: {{{shutdown,{failed_to_start_child,'Elixir.TSE.Consumer',{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'tse_exchange' in vhost 'fffdmiik': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.365.0>,{call,{'exchange.declare',0,<<"tse_exchange">>,<<"fanout">>,false,true,false,false,false,[]},none,<0.346.0>},70000]}}}},{'Elixir.TseApi.Application',start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [<0.324.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.326.0>,normal}]
    links: [<0.324.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 219
  neighbours:
2021-10-22 16:44:02 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.TseApi.Supervisor'}
     Context:    start_error
     Reason:     {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'tse_exchange' in vhost 'fffdmiik': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.365.0>,{call,{'exchange.declare',0,<<"tse_exchange">>,<<"fanout">>,false,false,false,false,false,[]},none,<0.346.0>},70000]}}
     Offender:   [{pid,undefined},{id,'Elixir.TSE.Consumer'},{mfargs,{'Elixir.TSE.Consumer',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2021-10-22 16:44:02 =CRASH REPORT====
  crasher:
    initial call: Elixir.TSE.Consumer:init/1
    pid: <0.346.0>
    registered_name: []
    exception exit: {{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'tse_exchange' in vhost 'fffdmiik': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.365.0>,{call,{'exchange.declare',0,<<"tse_exchange">>,<<"fanout">>,false,false,false,false,false,[]},none,<0.346.0>},70000]}},[{gen_server,call,3,[{file,"gen_server.erl"},{line,223}]},{'Elixir.AMQP.Exchange',declare,4,[{file,"lib/amqp/exchange.ex"},{line,48}]},{'Elixir.TSE.Consumer',setup_exchange,1,[{file,"lib/tse_api/consumer.ex"},{line,46}]},{'Elixir.TSE.Consumer',init,1,[{file,"lib/tse_api/consumer.ex"},{line,17}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: ['Elixir.TseApi.Supervisor',<0.326.0>]
    message_queue_len: 0
    messages: []
    links: [<0.327.0>]
    dictionary: [{gen_server_call_timeout,70000}]
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 44790
  neighbours:
2021-10-22 16:44:02 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.325.0>
    registered_name: []
    exception exit: {{{shutdown,{failed_to_start_child,'Elixir.TSE.Consumer',{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'tse_exchange' in vhost 'fffdmiik': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.365.0>,{call,{'exchange.declare',0,<<"tse_exchange">>,<<"fanout">>,false,false,false,false,false,[]},none,<0.346.0>},70000]}}}},{'Elixir.TseApi.Application',start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [<0.324.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.326.0>,normal}]
    links: [<0.324.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 220
  neighbours:
2021-10-22 16:46:56 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.TseApi.Supervisor'}
     Context:    start_error
     Reason:     {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'tse_exchange' in vhost 'fffdmiik': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.365.0>,{call,{'exchange.declare',0,<<"tse_exchange">>,<<"fanout">>,false,false,false,false,false,[]},none,<0.346.0>},70000]}}
     Offender:   [{pid,undefined},{id,'Elixir.TSE.Consumer'},{mfargs,{'Elixir.TSE.Consumer',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2021-10-22 16:46:56 =CRASH REPORT====
  crasher:
    initial call: Elixir.TSE.Consumer:init/1
    pid: <0.346.0>
    registered_name: []
    exception exit: {{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'tse_exchange' in vhost 'fffdmiik': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.365.0>,{call,{'exchange.declare',0,<<"tse_exchange">>,<<"fanout">>,false,false,false,false,false,[]},none,<0.346.0>},70000]}},[{gen_server,call,3,[{file,"gen_server.erl"},{line,223}]},{'Elixir.AMQP.Exchange',declare,4,[{file,"lib/amqp/exchange.ex"},{line,48}]},{'Elixir.TSE.Consumer',setup_exchange,1,[{file,"lib/tse_api/consumer.ex"},{line,46}]},{'Elixir.TSE.Consumer',init,1,[{file,"lib/tse_api/consumer.ex"},{line,17}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: ['Elixir.TseApi.Supervisor',<0.326.0>]
    message_queue_len: 0
    messages: []
    links: [<0.327.0>]
    dictionary: [{gen_server_call_timeout,70000}]
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 44790
  neighbours:
2021-10-22 16:46:56 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.325.0>
    registered_name: []
    exception exit: {{{shutdown,{failed_to_start_child,'Elixir.TSE.Consumer',{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'tse_exchange' in vhost 'fffdmiik': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.365.0>,{call,{'exchange.declare',0,<<"tse_exchange">>,<<"fanout">>,false,false,false,false,false,[]},none,<0.346.0>},70000]}}}},{'Elixir.TseApi.Application',start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [<0.324.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.326.0>,normal}]
    links: [<0.324.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 219
  neighbours:
2021-10-22 16:47:55 =CRASH REPORT====
  crasher:
    initial call: Elixir.TSE.Consumer:init/1
    pid: <0.346.0>
    registered_name: []
    exception exit: {{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'tse_exchange' in vhost 'fffdmiik': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.365.0>,{call,{'exchange.declare',0,<<"tse_exchange">>,<<"fanout">>,false,false,false,false,false,[]},none,<0.346.0>},70000]}},[{gen_server,call,3,[{file,"gen_server.erl"},{line,223}]},{'Elixir.AMQP.Exchange',declare,4,[{file,"lib/amqp/exchange.ex"},{line,48}]},{'Elixir.TSE.Consumer',setup_exchange,1,[{file,"lib/tse_api/consumer.ex"},{line,42}]},{'Elixir.TSE.Consumer',init,1,[{file,"lib/tse_api/consumer.ex"},{line,17}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: ['Elixir.TseApi.Supervisor',<0.326.0>]
    message_queue_len: 0
    messages: []
    links: [<0.327.0>]
    dictionary: [{gen_server_call_timeout,70000}]
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 44170
  neighbours:
2021-10-22 16:47:55 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.TseApi.Supervisor'}
     Context:    start_error
     Reason:     {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'tse_exchange' in vhost 'fffdmiik': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.365.0>,{call,{'exchange.declare',0,<<"tse_exchange">>,<<"fanout">>,false,false,false,false,false,[]},none,<0.346.0>},70000]}}
     Offender:   [{pid,undefined},{id,'Elixir.TSE.Consumer'},{mfargs,{'Elixir.TSE.Consumer',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2021-10-22 16:47:55 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.325.0>
    registered_name: []
    exception exit: {{{shutdown,{failed_to_start_child,'Elixir.TSE.Consumer',{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'tse_exchange' in vhost 'fffdmiik': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.365.0>,{call,{'exchange.declare',0,<<"tse_exchange">>,<<"fanout">>,false,false,false,false,false,[]},none,<0.346.0>},70000]}}}},{'Elixir.TseApi.Application',start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [<0.324.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.326.0>,normal}]
    links: [<0.324.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 219
  neighbours:
2021-10-22 16:51:45 =CRASH REPORT====
  crasher:
    initial call: Elixir.TSE.Consumer:init/1
    pid: <0.346.0>
    registered_name: []
    exception exit: {{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'tse_exchange' in vhost 'fffdmiik': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.365.0>,{call,{'exchange.declare',0,<<"tse_exchange">>,<<"fanout">>,false,true,false,false,false,[]},none,<0.346.0>},70000]}},[{gen_server,call,3,[{file,"gen_server.erl"},{line,223}]},{'Elixir.AMQP.Exchange',declare,4,[{file,"lib/amqp/exchange.ex"},{line,48}]},{'Elixir.TSE.Consumer',setup_exchange,1,[{file,"lib/tse_api/consumer.ex"},{line,46}]},{'Elixir.TSE.Consumer',init,1,[{file,"lib/tse_api/consumer.ex"},{line,17}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: ['Elixir.TseApi.Supervisor',<0.326.0>]
    message_queue_len: 0
    messages: []
    links: [<0.327.0>]
    dictionary: [{gen_server_call_timeout,70000}]
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 44790
  neighbours:
2021-10-22 16:51:45 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.TseApi.Supervisor'}
     Context:    start_error
     Reason:     {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'tse_exchange' in vhost 'fffdmiik': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.365.0>,{call,{'exchange.declare',0,<<"tse_exchange">>,<<"fanout">>,false,true,false,false,false,[]},none,<0.346.0>},70000]}}
     Offender:   [{pid,undefined},{id,'Elixir.TSE.Consumer'},{mfargs,{'Elixir.TSE.Consumer',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2021-10-22 16:51:45 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.325.0>
    registered_name: []
    exception exit: {{{shutdown,{failed_to_start_child,'Elixir.TSE.Consumer',{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'tse_exchange' in vhost 'fffdmiik': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.365.0>,{call,{'exchange.declare',0,<<"tse_exchange">>,<<"fanout">>,false,true,false,false,false,[]},none,<0.346.0>},70000]}}}},{'Elixir.TseApi.Application',start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [<0.324.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.326.0>,normal}]
    links: [<0.324.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 219
  neighbours:
2021-10-22 16:54:20 =CRASH REPORT====
  crasher:
    initial call: Elixir.TSE.Consumer:init/1
    pid: <0.346.0>
    registered_name: []
    exception exit: {{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'tse_exchange' in vhost 'fffdmiik': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.365.0>,{call,{'exchange.declare',0,<<"tse_exchange">>,<<"fanout">>,false,false,false,false,false,[]},none,<0.346.0>},70000]}},[{gen_server,call,3,[{file,"gen_server.erl"},{line,223}]},{'Elixir.AMQP.Exchange',declare,4,[{file,"lib/amqp/exchange.ex"},{line,48}]},{'Elixir.TSE.Consumer',setup_exchange,1,[{file,"lib/tse_api/consumer.ex"},{line,42}]},{'Elixir.TSE.Consumer',init,1,[{file,"lib/tse_api/consumer.ex"},{line,17}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: ['Elixir.TseApi.Supervisor',<0.326.0>]
    message_queue_len: 0
    messages: []
    links: [<0.327.0>]
    dictionary: [{gen_server_call_timeout,70000}]
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 44170
  neighbours:
2021-10-22 16:54:20 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.TseApi.Supervisor'}
     Context:    start_error
     Reason:     {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'tse_exchange' in vhost 'fffdmiik': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.365.0>,{call,{'exchange.declare',0,<<"tse_exchange">>,<<"fanout">>,false,false,false,false,false,[]},none,<0.346.0>},70000]}}
     Offender:   [{pid,undefined},{id,'Elixir.TSE.Consumer'},{mfargs,{'Elixir.TSE.Consumer',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2021-10-22 16:54:20 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.325.0>
    registered_name: []
    exception exit: {{{shutdown,{failed_to_start_child,'Elixir.TSE.Consumer',{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'tse_exchange' in vhost 'fffdmiik': received 'fanout' but current is 'direct'">>}},{gen_server,call,[<0.365.0>,{call,{'exchange.declare',0,<<"tse_exchange">>,<<"fanout">>,false,false,false,false,false,[]},none,<0.346.0>},70000]}}}},{'Elixir.TseApi.Application',start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [<0.324.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.326.0>,normal}]
    links: [<0.324.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 219
  neighbours:
2021-10-22 16:56:26 =SUPERVISOR REPORT====
     Supervisor: {local,'Elixir.TseApi.Supervisor'}
     Context:    start_error
     Reason:     {'EXIT',{undef,[{'Elixir.TSE.Consumer',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,379}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,349}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1157}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,315}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]}]}}
     Offender:   [{pid,undefined},{id,'Elixir.TSE.Consumer'},{mfargs,{'Elixir.TSE.Consumer',start_link,[[]]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2021-10-22 16:56:26 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.325.0>
    registered_name: []
    exception exit: {{{shutdown,{failed_to_start_child,'Elixir.TSE.Consumer',{'EXIT',{undef,[{'Elixir.TSE.Consumer',start_link,[[]],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,379}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,'-start_children/2-fun-0-',3,[{file,"supervisor.erl"},{line,349}]},{supervisor,children_map,4,[{file,"supervisor.erl"},{line,1157}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,315}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]}]}}}},{'Elixir.TseApi.Application',start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
    ancestors: [<0.324.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.326.0>,normal}]
    links: [<0.324.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 247
  neighbours:
